// src/components/SocialLink.tsx
import { useState } from 'react'
import { Icon } from '@iconify/react'

interface SocialLinkProps {
    href: string
    label: string
    iconClass: string
}

export default function SocialLink({ href, label, iconClass }: SocialLinkProps) {
    const [hovered, setHovered] = useState(false)

    return (
        <a
            href={href}
            className="lg:text-3xl text-2xl hover:text-red-600 transition-colors inline-block"
            aria-label={label}
            style={{
                transform: hovered ? 'scale(1.25)' : 'scale(1)',
                transition: 'transform 0.2s ease, color 0.2s ease',
            }}
            onMouseEnter={() => setHovered(true)}
            onMouseLeave={() => setHovered(false)}
        >
            <Icon icon={iconClass} />
        </a>
    )
}

// src/routes/SocialLink.svelte
<script lang="ts">
  import {spring} from "svelte/motion";
  import Icon from "@iconify/svelte";
  let scale=spring(1,{stiffness:0.1,damping:0.4})

  let {href,label,iconClass} =$props()
</script>


<a
      href={href}
      class="lg:text-3xl md:text-2xl text-xl hover:text-red-600 transition-colors duration-300 inline-block"
      aria-label={label}
      style="transform: scale({$scale});"
      onmouseenter={() => scale.set(1.25)}
      onmouseleave={() => scale.set(1)}
>
  <Icon icon={iconClass}/>
</a>
